<?php
/**
 * Web30india Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://web30india.com/web30india-Commerce-License.txt
 *
 * @category   Web30india
 * @package    Web30india_Quickview
 * @author     Extension Team
 * @copyright  Copyright (c) 2009-2022 Web30india Commerce Co. (https://web30india.com )
 * @license    https://web30india.com/web30india-Commerce-License.txt
 */
// @codingStandardsIgnoreFile
?>
<?php
/**
 * @var \Web30india\Quickview\Block\Initialize $block
 */
?>
<?php $product = $block->getProduct(); ?>
<?php
    $helper = $block->getHelper();
    $removeReview = $helper->getRemoveReview();
    $removeMoreInfo = $helper->getRemoveMoreInfo();
?>

<script type="text/x-magento-init">
    {
        "*": {
            "Web30india_Quickview/js/web30india_beforebodyend": {
                "removeReview": "<?php echo $removeReview; ?>",
                "removeMoreInfo": "<?php echo $removeMoreInfo; ?>"
            }
        }
    }
</script>
