<?php
/**
 * Web30india Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://web30india.com/web30india-Commerce-License.txt
 *
 * @category   Web30india
 * @package    Web30india_Quickview
 * @author     Extension Team
 * @copyright  Copyright (c) 2009-2022 Web30india Commerce Co. (https://web30india.com )
 * @license    https://web30india.com/web30india-Commerce-License.txt
 */
// @codingStandardsIgnoreFile
?>
<?php
/**
 * @var \Web30india\Quickview\Block\Initialize $block
 */
?>
<?php
$helper = $block->getHelper();
$btnTextColor = $helper->getBtnTextColor();
$baseUrl = $helper->getBaseUrl();
$buttonText = $helper->getButtonText();
$btnBackground = $helper->getBtnBackground();
list($r, $g, $b) = sscanf($btnBackground, "%02x%02x%02x");
$productUrl = $helper->getUrl();
$buttonText = $helper->getButtonText();
$isEnabled = $helper->enabled();
$productItemInfo = $helper->getProductItemInfo();
$productImageWrapper = $helper->getProductImageWrapper();
?>

<style>
    a.web30india-quickview{
        color: #<?php echo $btnTextColor; ?>;
        background-color: rgba(<?php echo "$r , $g , $b"; ?>,0.6);
    }
    a.web30india-quickview {
        position: absolute;
        display: block;
        bottom: 0px;
        padding: 3px 10px;
        margin-left: auto;
        margin-right: auto;
        left: 0;
        right: 0;
        }
    .product-item .product-item-info:hover .web30india-quickview{
        display: block !important;
        position: absolute !important;
        bottom: 0px !important;
        left: 0px !important;
        margin: 0;
        z-index: 99999999999999 !important;
        width: 100% !important;
        padding: 10px 0 10px 0;
        text-align: center !important;
        font-size: 14px !important;
        text-decoration: none !important;
    }

    .product-item .product-item-info:hover .web30india-quickview{
        display: block !important;
        position: absolute !important;
        bottom: 0px !important;
        left: 0px !important;
        margin: 0;
        z-index: 99999999999999 !important;
        width: 100% !important;
        padding: 10px 0 10px 0;
        text-align: center !important;
        font-size: 14px !important;
        text-decoration: none !important;
    }
    .product-item .web30india-quickview {display: none !important}
    #shopping-cart-table .web30india-quickview {display: none !important}
    .products-related .product-item-info:hover .web30india-quickview, .products-upsell .product-item-info:hover .web30india-quickview {display: none !important}
</style>
<script type="text/x-magento-init">
    {
        "*": {
            "Web30india_Quickview/js/web30india_config": {
                "productUrl": "<?php echo $productUrl; ?>",
                "buttonText": "<?php echo $buttonText; ?>",
                "isEnabled": "<?php echo $isEnabled; ?>",
                "baseUrl": "<?php echo $baseUrl; ?>",
                "productItemInfo": "<?php echo $productItemInfo; ?>",
                "productImageWrapper": "<?php echo $productImageWrapper; ?>"
            }
        }
    }
</script>
