<?php
/**
 * Web30india Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://web30india.com/web30india-Commerce-License.txt
 *
 * @category   Web30india
 * @package    Web30india_Quickview
 * @author     Extension Team
 * @copyright  Copyright (c) 2009-2022 Web30india Commerce Co. (https://web30india.com )
 * @license    https://web30india.com/web30india-Commerce-License.txt
 */
// @codingStandardsIgnoreFile
?>
<?php
/**
 * @var Magento\Catalog\Block\Product\View\Type\Simple $block
 */
?>
<?php $product = $block->getProduct();
?>
<div id="ajax-goto">
    <a class="goto-product" href="<?php echo $product->getUrlModel()->getUrl($product);?>">
        <span><?php echo __('Go to Product'); ?></span>
    </a>
</div>
